<a href="https://colab.research.google.com/github/KrisGajda/Data-science-bootcamp-Krakowiak/blob/main/Data_science_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tworzenie obiektu typu array (tablicy)

In [1]:
import numpy as np
A = np.array([1, 2, 3], dtype='float') # utworzenie tablicy jednowymiarowej typu float
A.dtype

dtype('float64')

In [ ]:
A = np.array([24, 120, 220], dtype=np.int16)
A.dtype

dtype('int16')

In [ ]:
X = np.zeros(shape=(3, 5)) # utworzenie tablicy zer o kształcie 3x5
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
E = np.ones(shape=(3, 5)) # utworzenie tablicy jedynek o kształcie 3x5
E

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
Y = np.full(shape=(5, 5), fill_value=4) # utworzenie tablicy o danym kształcie i wypełnionej określonymi wartościami
Y

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
import numpy as np
A = np.arange(120) # utwórz tabelę 120-elementową
A.reshape((10, -1)) # ... okształcie: 10 wierszy , dopasuj ilość kolumn (-1)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [ ]:
A.reshape((-1, 12)) # dopasuj ilość wierszy do dwunastu kolumn

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

Działania arytmetyczne na tabelach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
np.add(A, B) # funkcja add() - dodawanie tablic

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
np.subtract(A, B) # funkcja substrackt() - odejmownanie tablic

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
np.multiply(A, B) # funkcja multiply() - mnożenie tablic (nie macieżowe!)

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.divide(A, B) # funcja divide() - dzielenie tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A+3 # dodawanie określonej wartości do każdego elementu tablicy

array([6, 4, 7, 5])

In [ ]:
A*2 # mnożenie przez daną wartość każdego elementu tablicy

array([6, 2, 8, 4])

In [ ]:
A+3*B # dodawanie do tablicy pomnożonej wartości innej tablicy

array([12, -2, 13,  8])

Mnożenie macieżowe

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X, Y) # mnożenie maacieżowe -> wiersz x kolumna

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y) # to samo co wyżej - UWAGA mnożenie macieży nie jest przemienne!

array([[  3,   6],
       [-12,   0]])

In [ ]:
X @ Y # rownież zapis mnożenia macieży

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0) # ziarno losowania

In [ ]:
np.random.randn() # losowy rozkład normalny

-1.4203853924563898

In [ ]:
np.random.randn(10) # tablica dziesięciu losowo wygenerowanych elementów z rozkładu normalnego standardowego (średnia 0 i odchylenie standardowe 1)

array([ 1.23112814,  1.38117045,  0.24070787,  0.2663047 , -0.50172243,
       -0.69298896,  1.34720025, -1.16822497, -0.68816014, -0.93776055])

In [ ]:
np.random.randn(10, 4) # macierz 10x4 losowych elementów z rozkładu normalnego standardowego. Może pomóc u stworzeniu histogramów rozkładu normalnego

array([[-1.47121739,  0.53563708,  1.27565831,  0.19329796],
       [ 0.06765002,  0.24054598,  0.60582126, -1.14931624],
       [-0.42343423,  2.53891024, -0.24200525,  2.63046348],
       [ 0.55749314,  0.022744  ,  0.52464761, -0.78699184],
       [-0.17945565, -0.72806077,  0.67291054,  1.23191456],
       [ 0.39333837,  0.2160677 , -1.33647448, -0.17117138],
       [ 1.55204749, -1.04981028,  1.33420541,  1.17723575],
       [ 0.41030793, -0.65994486, -1.81798665,  0.39270413],
       [ 0.2454609 , -1.08148767,  0.31181014, -1.58643203],
       [ 2.0537817 , -1.47306602, -0.48511758, -0.42904267]])

In [ ]:
np.random.rand() # losowa liczba z przedziału <0, 1). Rozkład jednostajny na przedziale

0.8433234053899142

In [ ]:
np.random.rand(10) # tablica dziesięciu losowo wygenerowanych elementów z rozkładu jednostajnego na przedziale <0, 1>

array([0.9005864 , 0.37657854, 0.71657664, 0.9181458 , 0.4200413 ,
       0.56290745, 0.63404594, 0.59449131, 0.37475465, 0.65383078])

In [ ]:
np.random.rand(10, 2) # tablica 2-wymiarowa 10x2

array([[0.80678897, 0.40994627],
       [0.81857522, 0.14682224],
       [0.81958112, 0.81572207],
       [0.29267129, 0.5411947 ],
       [0.11669356, 0.53908661],
       [0.43491764, 0.90464792],
       [0.57718927, 0.18606154],
       [0.07200331, 0.17981189],
       [0.04227584, 0.02543929],
       [0.09774377, 0.62876082]])

In [ ]:
np.random.randint(10) # losowa liczba całkowita z przedziału <0, 10)

5

In [ ]:
np.random.randint(low=10, high=101) # losowa liczba całkowita z przedziału <10, 101)

96

In [ ]:
np.random.randint(low=10, high=101, size=10) # tablica dziesięciu losowo wygenerowanych liczb całkowitych z przedziału <10, 101)

array([85, 60, 95, 47, 32, 83, 50, 71, 38, 26])

In [ ]:
np.random.choice([4, 2, 1, 3, 5]) # losowy element z listy

np.int64(1)

In [ ]:
np.random.choice(['python', 'java', 'sql']) # losowy element z listy

np.str_('sql')

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data) # losowa permutacja. Funkcja działa na oryginale zmiennej! W bibliotece pandas podobna funkcja zachodzi na kopii zmiennej - nie rusza oryginału!
data

array([6, 5, 3, 4, 0, 7, 1, 2, 8, 9])

Podstawowe funkcje w bibliotece NumPy

In [ ]:
np.exp(1) # Funkcja exponent. e do potęgi x

np.float64(2.718281828459045)

In [ ]:
np.sqrt(9) # pierwiastek kwadratowy. Zwraca zawsze w typie float

np.float64(3.0)

In [ ]:
np.all([2, 3, 1]) # funkcja przechodzi po wszystkich elementach listy i bada każdy element, czy zwraca wartość logiczną True, czy False. Wszystkie True -> wynik True

np.True_

In [ ]:
np.any([0, 0, 0]) # funkcja sprawdza, czy jakikolwiek obiekt jest prawdą - tutaj każdy jest fałszem -> 0

np.False_

In [ ]:
A = np.random.rand(5) # 5 wartości z rozkładu jednostajnego
A

array([0.66590767, 0.35018836, 0.56648665, 0.61543963, 0.22124149])

In [ ]:
np.argmax(A) # zwraca indeks największej wartości

np.int64(0)

In [ ]:
A[np.argmax(A)] # zwraca największą wartość

np.float64(0.6659076712591298)

In [ ]:
np.argmin(A) # zwraca indeks najmniejszej wartości

np.int64(4)

In [ ]:
np.argsort(A) # zwraca indeksy posortowanych wartości - sortuje rosnąco

array([4, 1, 2, 3, 0])

In [ ]:
np.max(A) # zwraca największą wartość

np.float64(0.6659076712591298)

In [ ]:
np.min(A) # zwraca najmniejszą wartość

np.float64(0.2212414938194126)

In [ ]:
np.mean(A) # zwraca średnią arytmetyczną

np.float64(0.4838527609650691)

In [ ]:
np.median(A) # mediana

np.float64(0.5664866479668528)

In [ ]:
np.std(A) # odchylenie standardowe

np.float64(0.2838992013095173)

Indeksowanie, wycinanie danych

In [ ]:
R = np.random.randn(100) # wygenerowanie tablicy 100 losowych elementów z rozkładu normalnego standardowego
R = R.reshape(10, 10) # zmiana kształtu tablicy na macież (tablica 2-wymiarowa) o kształcie 10x10
R

array([[ 0.14736869,  1.60030513,  1.08979824, -0.81061051,  0.39920186,
        -0.38314549,  3.4449345 , -0.21076715, -0.73907123, -1.26874564],
       [-1.127741  , -1.27545693,  0.08011226, -1.75574992, -0.45495324,
         0.86339758,  1.83734393,  1.23949003, -0.837993  , -1.67161522],
       [ 0.18065208, -0.06457892, -0.92332697,  0.04913395,  0.66668419,
         0.53106387,  0.93647113, -0.36361412, -1.85585521,  0.55841812],
       [-0.39894505, -1.12141873, -0.24119549, -0.17455319,  1.36553549,
        -1.48450598, -0.12446214,  1.67526361,  0.89918103,  0.34001366],
       [-1.42359437,  0.18667371,  0.52936991, -2.12252225,  0.16984852,
        -0.36892098, -0.19689091,  0.05017624, -0.26883633,  0.09584642],
       [-0.32646454, -0.44166508,  2.38175426, -0.68983037, -0.43082332,
         1.03766722, -0.7605095 , -0.27530133,  0.34494126, -0.5667757 ],
       [-0.39829356,  0.88437896, -0.85418425, -0.69631441,  0.19215212,
         0.75985367, -0.07478833, -1.31876623

In [ ]:
R[0] # wycięcie elementu "zerowego" (index) tablicy R, czyli tutaj pierwszego wiersza tablicy R

array([ 0.14736869,  1.60030513,  1.08979824, -0.81061051,  0.39920186,
       -0.38314549,  3.4449345 , -0.21076715, -0.73907123, -1.26874564])

In [ ]:
R[1:3] # wycięcie wierszy o indeksach od 1 do 2 (bez 3!);
# R[:stop] - wszystkie indeksy od początku do stop-1;
# R[start:] - wszystkie indeksy od wybranego do końca

array([[-1.127741  , -1.27545693,  0.08011226, -1.75574992, -0.45495324,
         0.86339758,  1.83734393,  1.23949003, -0.837993  , -1.67161522],
       [ 0.18065208, -0.06457892, -0.92332697,  0.04913395,  0.66668419,
         0.53106387,  0.93647113, -0.36361412, -1.85585521,  0.55841812]])

In [ ]:
R[1, 3] # wycina wartość z wiersza o indexie 1 i wartość kolumny o indeksie 3

np.float64(-1.7557499218466404)

In [ ]:
Z = R[0] # wycina 0 element tablicy R (mamy więc tablicę 1-wymiarową)
Z
Z[[0, 2, 4, 6]] # wycina elementy o indeksach 0 i 2 z nowej tablicy Z

array([0.14736869, 1.08979824, 0.39920186, 3.4449345 ])

In [ ]:
Z[-1] # zwraca ostatni element tablicy

np.float64(-1.268745638916911)

In [ ]:
R[:, 1] # wycięcie kolumny o indeksie 1

array([ 0.14736869, -1.127741  ,  0.18065208, -0.39894505, -1.42359437,
       -0.32646454, -0.39829356,  1.31254493,  0.13741689,  0.04390206])

In [12]:
L = np.random.randint(low=0, high=30, size=20)
L
L = L.reshape(4, 5)
L


array([[28,  4, 24, 25, 18],
       [24, 11,  7, 12, 22],
       [ 5,  4, 27,  1, 14],
       [14, 13, 10, 24, 25]])

In [11]:
M = L[1:3, 1:4] # wycięcie z tablicy L wartości z wierszy o indeksach 1-2 i kolumn o indeksach 1-3

In [13]:
M

array([[15,  4,  5],
       [10,  1, 28]])

In [14]:
M[1, 1] = 20 # przypisanie do indeksu 1,1 tablicy M wartości 20
M

array([[15,  4,  5],
       [10, 20, 28]])

Iteracja po tablicach

In [17]:
L = np.random.randint(low=0, high=30, size=20)
L = L.reshape(4, 5)
L


array([[ 1, 23, 23,  7, 20],
       [26, 25, 17, 18, 20],
       [24, 29,  6, 24, 22],
       [ 7, 26, 15, 25, 10]])

In [18]:
for row in L: # iteracja po wierszu
  print(row)

[ 1 23 23  7 20]
[26 25 17 18 20]
[24 29  6 24 22]
[ 7 26 15 25 10]


In [19]:
for row in L:
  print(row[1]) # iteracja po elementach wierszy o wybranym indeksie

23
25
29
26


In [20]:
for row in L: # iteracja po wierszu
  print(row[:3]) # iteracja po 3 pierwszych wierszach

[ 1 23 23]
[26 25 17]
[24 29  6]
[ 7 26 15]


In [22]:
for item in L.flat: # iterowanie po każdym elemencie tablicy po wypłaszczeniu tablicy (flat() )
  print(item)

1
23
23
7
20
26
25
17
18
20
24
29
6
24
22
7
26
15
25
10


Zmiana rozmiaru tablic

In [23]:
L = np.random.randint(low=0, high=30, size=20)
L = L.reshape(4, 5)
L

array([[13,  4, 24, 13,  3],
       [ 0, 23, 20, 27, 13],
       [29, 21, 10,  9,  9],
       [25, 18, 11, 12,  4]])

In [25]:
L.reshape(5, 4)

array([[13,  4, 24, 13],
       [ 3,  0, 23, 20],
       [27, 13, 29, 21],
       [10,  9,  9, 25],
       [18, 11, 12,  4]])

In [26]:
L.ravel() # funkcja ravel() wypłaszcza tablicę

array([13,  4, 24, 13,  3,  0, 23, 20, 27, 13, 29, 21, 10,  9,  9, 25, 18,
       11, 12,  4])

In [ ]:
L.T # transponowanie tablicy - zamiana wierszy na kolumny

Maski logiczne

In [28]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [29]:
A>0 # nałożona maska logiczna z określonym warunkiem - zwraca True lub False w zależności od spełnionego warunku

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
A[A > 0] # wycięcie z tablicy określonych wartości w zależności od spełnienia warunku

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [31]:
A[np.bitwise_and(A > -5, A < 5)] # łączenie warunków - funkcja bitwise_and

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [32]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])